export interface AdCampaign extends Record<string, unknown> {
  id: string;
  platform: string;
  name: string;
  logo: string;
  launched: string;
  impressions: number;
  clicks: number;
  status: 'Active' | 'Pending' | 'Inactive';
}

export const adCampaignsMockup: AdCampaign[] = [
  {
    id: '1',
    platform: 'Google Ads',
    name: 'Search Campaign - E-commerce',
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=GoogleAds&backgroundColor=4285f4',
    launched: 'Since Jan 2024',
    impressions: 1250000,
    clicks: 45200,
    status: 'Active',
  },
  {
    id: '2',
    platform: 'Facebook Ads',
    name: 'Conversion Campaign - Fashion',
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=FacebookAds&backgroundColor=1877f2',
    launched: 'Since Mar 2024',
    impressions: 980000,
    clicks: 32100,
    status: 'Active',
  },
  {
    id: '3',
    platform: 'Instagram Ads',
    name: 'Brand Awareness - Lifestyle',
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=InstagramAds&backgroundColor=e4405f',
    launched: 'Since Feb 2024',
    impressions: 750000,
    clicks: 28500,
    status: 'Pending',
  },
  {
    id: '4',
    platform: 'TikTok Ads',
    name: 'Video Ads - Gen Z Products',
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=TikTokAds&backgroundColor=000000',
    launched: 'Since Apr 2024',
    impressions: 2100000,
    clicks: 89000,
    status: 'Inactive',
  },
  {
    id: '5',
    platform: 'LinkedIn Ads',
    name: 'B2B Lead Generation',
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=LinkedInAds&backgroundColor=0a66c2',
    launched: 'Since May 2024',
    impressions: 450000,
    clicks: 15600,
    status: 'Active',
  },
  {
    id: '6',
    platform: 'Twitter/X Ads',
    name: 'Engagement Campaign - Tech',
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=TwitterAds&backgroundColor=000000',
    launched: 'Since Jan 2024',
    impressions: 620000,
    clicks: 21400,
    status: 'Active',
  },
  {
    id: '7',
    platform: 'YouTube Ads',
    name: 'Video Discovery - Entertainment',
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=YouTubeAds&backgroundColor=ff0000',
    launched: 'Since Feb 2024',
    impressions: 1800000,
    clicks: 72000,
    status: 'Pending',
  },
  {
    id: '8',
    platform: 'Pinterest Ads',
    name: 'Shopping Ads - Home Decor',
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=PinterestAds&backgroundColor=bd081c',
    launched: 'Since Mar 2024',
    impressions: 540000,
    clicks: 19800,
    status: 'Active',
  },
  {
    id: '9',
    platform: 'Snapchat Ads',
    name: 'Story Ads - Youth Fashion',
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=SnapchatAds&backgroundColor=fffc00',
    launched: 'Since Apr 2024',
    impressions: 890000,
    clicks: 34500,
    status: 'Active',
  },
  {
    id: '10',
    platform: 'Reddit Ads',
    name: 'Community Engagement - Gaming',
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=RedditAds&backgroundColor=ff4500',
    launched: 'Since Jan 2024',
    impressions: 320000,
    clicks: 12800,
    status: 'Inactive',
  },
  {
    id: '11',
    platform: 'Amazon Ads',
    name: 'Sponsored Products - Electronics',
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=AmazonAds&backgroundColor=ff9900',
    launched: 'Since May 2024',
    impressions: 1450000,
    clicks: 58200,
    status: 'Active',
  },
  {
    id: '12',
    platform: 'Bing Ads',
    name: 'Search Network - Services',
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=BingAds&backgroundColor=008373',
    launched: 'Since Feb 2024',
    impressions: 380000,
    clicks: 13300,
    status: 'Active',
  },
  {
    id: '13',
    platform: 'Display Network',
    name: 'Banner Ads - Travel',
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=DisplayAds&backgroundColor=34a853',
    launched: 'Since Mar 2024',
    impressions: 2300000,
    clicks: 69000,
    status: 'Pending',
  },
  {
    id: '14',
    platform: 'Programmatic',
    name: 'RTB Campaign - Automotive',
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=ProgrammaticAds&backgroundColor=9c27b0',
    launched: 'Since Apr 2024',
    impressions: 1680000,
    clicks: 50400,
    status: 'Active',
  },
  {
    id: '15',
    platform: 'Native Ads',
    name: 'Content Discovery - News',
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=NativeAds&backgroundColor=00bcd4',
    launched: 'Since May 2024',
    impressions: 920000,
    clicks: 36800,
    status: 'Active',
  },
];

export const adCampaignsStats = {
  activeCampaigns: 69,
  totalCampaigns: 102,
};
