import type { Betting } from '@/models/betting.model';
import type { TotalCardData } from '@/models/dashboard/total-card.model';

export const bettingMockup: Betting[] = [
  {
    id: '1',
    platformName: 'BetKing VN',
    domain: 'betking.vn',
    logo: 'https://picsum.photos/seed/betking/100',
    category: 'Sports Betting',
    type: 'KOL',
    status: 'Active',
    monthlyUsers: 125000,
    activeUsers: 45000,
    totalBets: 3500000,
    revenue: 850000,
    commission: 127500,
    commissionRate: 15,
    conversionRate: 36,
    partnerName: 'Nguyễn Văn A (KOL Sports)',
    partnerType: 'KOL',
    contactPerson: 'Trần Thị B',
    contactEmail: 'contact@betking.vn',
    phone: '+84 901 234 567',
    country: 'Vietnam',
    language: 'Vietnamese',
    paymentStatus: 'Paid',
    paymentMethod: 'Bank Transfer',
    lastPaymentDate: '2025-10-01',
    nextPaymentDate: '2025-11-01',
    totalPaid: 1200000,
    dateAdded: '2024-01-15',
    lastUpdated: '2025-10-13',
    riskLevel: 'Low',
    notes: 'Top performing KOL partnership',
  },
  {
    id: '2',
    platformName: 'Lucky Casino 88',
    domain: 'lucky88.com',
    logo: 'https://picsum.photos/seed/lucky88/100',
    category: 'Casino',
    type: 'Outsource',
    status: 'Active',
    monthlyUsers: 98000,
    activeUsers: 32000,
    totalBets: 2800000,
    revenue: 680000,
    commission: 102000,
    commissionRate: 15,
    conversionRate: 32.6,
    partnerName: 'Asia Gaming Agency',
    partnerType: 'Agency',
    contactPerson: 'David Lee',
    contactEmail: 'business@lucky88.com',
    phone: '+65 9876 5432',
    country: 'Singapore',
    language: 'English',
    paymentStatus: 'Pending',
    paymentMethod: 'Wire Transfer',
    lastPaymentDate: '2025-09-15',
    nextPaymentDate: '2025-10-15',
    totalPaid: 850000,
    dateAdded: '2024-03-10',
    lastUpdated: '2025-10-12',
    riskLevel: 'Medium',
    notes: 'Requires compliance check',
  },
  {
    id: '3',
    platformName: 'eSports Elite',
    domain: 'esportselite.gg',
    logo: 'https://picsum.photos/seed/esports/100',
    category: 'E-sports',
    type: 'KOL',
    status: 'Active',
    monthlyUsers: 150000,
    activeUsers: 68000,
    totalBets: 4200000,
    revenue: 920000,
    commission: 184000,
    commissionRate: 20,
    conversionRate: 45.3,
    partnerName: 'Streamer ProGamer123',
    partnerType: 'KOL',
    contactPerson: 'Kim Min-jun',
    contactEmail: 'contact@esportselite.gg',
    phone: '+82 10 1234 5678',
    country: 'South Korea',
    language: 'Korean',
    paymentStatus: 'Paid',
    paymentMethod: 'Crypto',
    lastPaymentDate: '2025-10-05',
    nextPaymentDate: '2025-11-05',
    totalPaid: 1500000,
    dateAdded: '2024-06-20',
    lastUpdated: '2025-10-14',
    riskLevel: 'Low',
    notes: 'Excellent performance, high conversion',
  },
  {
    id: '4',
    platformName: 'Poker Pro VN',
    domain: 'pokerpro.vn',
    logo: 'https://picsum.photos/seed/pokerpro/100',
    category: 'Poker',
    type: 'Direct',
    status: 'Active',
    monthlyUsers: 45000,
    activeUsers: 18000,
    totalBets: 1500000,
    revenue: 380000,
    commission: 76000,
    commissionRate: 20,
    conversionRate: 40,
    partnerName: 'Direct Partnership',
    partnerType: 'Direct',
    contactPerson: 'Lê Văn C',
    contactEmail: 'admin@pokerpro.vn',
    phone: '+84 902 345 678',
    country: 'Vietnam',
    language: 'Vietnamese',
    paymentStatus: 'Paid',
    paymentMethod: 'Bank Transfer',
    lastPaymentDate: '2025-10-01',
    nextPaymentDate: '2025-11-01',
    totalPaid: 650000,
    dateAdded: '2024-02-28',
    lastUpdated: '2025-10-13',
    riskLevel: 'Low',
  },
  {
    id: '5',
    platformName: 'MegaBet Asia',
    domain: 'megabet.asia',
    logo: 'https://picsum.photos/seed/megabet/100',
    category: 'Mixed',
    type: 'Outsource',
    status: 'Active',
    monthlyUsers: 210000,
    activeUsers: 85000,
    totalBets: 6500000,
    revenue: 1450000,
    commission: 217500,
    commissionRate: 15,
    conversionRate: 40.5,
    partnerName: 'Global Betting Solutions',
    partnerType: 'Agency',
    contactPerson: 'Michael Wong',
    contactEmail: 'partners@megabet.asia',
    phone: '+852 9123 4567',
    country: 'Hong Kong',
    language: 'English',
    paymentStatus: 'Paid',
    paymentMethod: 'Wire Transfer',
    lastPaymentDate: '2025-09-30',
    nextPaymentDate: '2025-10-30',
    totalPaid: 2100000,
    dateAdded: '2023-11-05',
    lastUpdated: '2025-10-14',
    riskLevel: 'Medium',
    notes: 'Large volume, requires monitoring',
  },
  {
    id: '6',
    platformName: 'VN Lottery Plus',
    domain: 'vnlottery.vn',
    logo: 'https://picsum.photos/seed/vnlottery/100',
    category: 'Lottery',
    type: 'KOL',
    status: 'Active',
    monthlyUsers: 180000,
    activeUsers: 95000,
    totalBets: 5200000,
    revenue: 780000,
    commission: 117000,
    commissionRate: 15,
    conversionRate: 52.8,
    partnerName: 'Influencer Lucky Star',
    partnerType: 'KOL',
    contactPerson: 'Phạm Thị D',
    contactEmail: 'info@vnlottery.vn',
    phone: '+84 903 456 789',
    country: 'Vietnam',
    language: 'Vietnamese',
    paymentStatus: 'Paid',
    paymentMethod: 'Bank Transfer',
    lastPaymentDate: '2025-10-02',
    nextPaymentDate: '2025-11-02',
    totalPaid: 980000,
    dateAdded: '2024-04-12',
    lastUpdated: '2025-10-13',
    riskLevel: 'Low',
  },
  {
    id: '7',
    platformName: 'Dragon Casino',
    domain: 'dragoncasino.com',
    logo: 'https://picsum.photos/seed/dragon/100',
    category: 'Casino',
    type: 'Outsource',
    status: 'Suspended',
    monthlyUsers: 75000,
    activeUsers: 15000,
    totalBets: 1800000,
    revenue: 320000,
    commission: 48000,
    commissionRate: 15,
    conversionRate: 20,
    partnerName: 'Asia Partners Ltd',
    partnerType: 'Agency',
    contactPerson: 'Chen Wei',
    contactEmail: 'contact@dragoncasino.com',
    phone: '+86 138 0000 0000',
    country: 'China',
    language: 'Chinese',
    paymentStatus: 'Overdue',
    paymentMethod: 'Wire Transfer',
    lastPaymentDate: '2025-08-01',
    nextPaymentDate: '2025-09-01',
    totalPaid: 450000,
    dateAdded: '2024-01-20',
    lastUpdated: '2025-10-10',
    riskLevel: 'High',
    notes: 'Payment issues, suspended until resolved',
  },
  {
    id: '8',
    platformName: 'Football Bet Pro',
    domain: 'footballbetpro.net',
    logo: 'https://picsum.photos/seed/football/100',
    category: 'Sports Betting',
    type: 'KOL',
    status: 'Active',
    monthlyUsers: 135000,
    activeUsers: 52000,
    totalBets: 3900000,
    revenue: 890000,
    commission: 178000,
    commissionRate: 20,
    conversionRate: 38.5,
    partnerName: 'Football Expert TV',
    partnerType: 'KOL',
    contactPerson: 'Nguyễn Văn E',
    contactEmail: 'business@footballbetpro.net',
    phone: '+84 904 567 890',
    country: 'Vietnam',
    language: 'Vietnamese',
    paymentStatus: 'Paid',
    paymentMethod: 'Bank Transfer',
    lastPaymentDate: '2025-10-03',
    nextPaymentDate: '2025-11-03',
    totalPaid: 1350000,
    dateAdded: '2024-05-15',
    lastUpdated: '2025-10-14',
    riskLevel: 'Low',
    notes: 'Football season performing well',
  },
  {
    id: '9',
    platformName: 'Royal Poker Club',
    domain: 'royalpoker.club',
    logo: 'https://picsum.photos/seed/royalpoker/100',
    category: 'Poker',
    type: 'Outsource',
    status: 'Pending',
    monthlyUsers: 28000,
    activeUsers: 8500,
    totalBets: 950000,
    revenue: 185000,
    commission: 27750,
    commissionRate: 15,
    conversionRate: 30.4,
    partnerName: 'Poker Network Int',
    partnerType: 'Affiliate',
    contactPerson: 'Sarah Johnson',
    contactEmail: 'partner@royalpoker.club',
    phone: '+44 20 7946 0958',
    country: 'United Kingdom',
    language: 'English',
    paymentStatus: 'Pending',
    paymentMethod: 'PayPal',
    lastPaymentDate: '2025-09-20',
    nextPaymentDate: '2025-10-20',
    totalPaid: 215000,
    dateAdded: '2024-07-01',
    lastUpdated: '2025-10-11',
    riskLevel: 'Medium',
    notes: 'New partnership, under evaluation',
  },
  {
    id: '10',
    platformName: 'Asian Sports Hub',
    domain: 'asiansportshub.com',
    logo: 'https://picsum.photos/seed/asiansports/100',
    category: 'Sports Betting',
    type: 'Direct',
    status: 'Active',
    monthlyUsers: 165000,
    activeUsers: 72000,
    totalBets: 4800000,
    revenue: 1120000,
    commission: 224000,
    commissionRate: 20,
    conversionRate: 43.6,
    partnerName: 'Direct Partnership',
    partnerType: 'Direct',
    contactPerson: 'Tanaka Hiroshi',
    contactEmail: 'admin@asiansportshub.com',
    phone: '+81 3 1234 5678',
    country: 'Japan',
    language: 'Japanese',
    paymentStatus: 'Paid',
    paymentMethod: 'Wire Transfer',
    lastPaymentDate: '2025-10-04',
    nextPaymentDate: '2025-11-04',
    totalPaid: 1890000,
    dateAdded: '2023-12-10',
    lastUpdated: '2025-10-14',
    riskLevel: 'Low',
    notes: 'Long-term trusted partner',
  },
];

export const totalCardsBettingMockup: TotalCardData[] = [
  {
    id: '1',
    title: 'Total Platforms',
    value: '10',
    icon: '',
    percentageChange: 12.5,
    changeLabel: 'Since last month',
  },
  {
    id: '2',
    title: 'Total Users',
    value: '1,211K',
    icon: '',
    percentageChange: 18.2,
    changeLabel: 'Since last month',
  },
  {
    id: '3',
    title: 'Total Revenue',
    value: '$7.57M',
    icon: '',
    percentageChange: 24.8,
    changeLabel: 'Since last month',
  },
  {
    id: '4',
    title: 'Total Commission',
    value: '$1.30M',
    icon: '',
    percentageChange: 22.3,
    changeLabel: 'Since last month',
  },
  {
    id: '5',
    title: 'Active Partnerships',
    value: '8',
    icon: '',
    percentageChange: 14.3,
    changeLabel: 'Since last month',
  },
  {
    id: '6',
    title: 'Avg Conversion Rate',
    value: '37.8%',
    icon: '',
    percentageChange: 8.5,
    changeLabel: 'Since last month',
  },
];
