export interface Brand extends Record<string, unknown> {
  id: string;
  category: string;
  name: string;
  logo: string;
  established: string;
  stores: number;
  products: number;
  status: 'Active' | 'Pending' | 'Inactive';
}

export const brandsMockup: Brand[] = [
  {
    id: '1',
    category: 'Electronics',
    name: 'ElectroMart - USA',
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=ElectroMart&backgroundColor=3b82f6',
    established: 'Since 2015',
    stores: 300,
    products: 5200,
    status: 'Active',
  },
  {
    id: '2',
    category: 'Furniture',
    name: 'FurniStyle - UK',
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=FurniStyle&backgroundColor=8b5cf6',
    established: 'Since 2010',
    stores: 120,
    products: 1100,
    status: 'Active',
  },
  {
    id: '3',
    category: 'Automotive',
    name: 'AutoGear - Germany',
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=AutoGear&backgroundColor=3b82f6',
    established: 'Since 2005',
    stores: 50,
    products: 850,
    status: 'Pending',
  },
  {
    id: '4',
    category: 'Fashion',
    name: 'StyleCore - Italy',
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=StyleCore&backgroundColor=3b82f6',
    established: 'Since 1998',
    stores: 200,
    products: 2300,
    status: 'Inactive',
  },
  {
    id: '5',
    category: 'Tech',
    name: 'TechVerse - India',
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=TechVerse&backgroundColor=8b5cf6',
    established: 'Since 2020',
    stores: 400,
    products: 7500,
    status: 'Active',
  },
  {
    id: '6',
    category: 'Home & Garden',
    name: 'HomeHub - Canada',
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=HomeHub&backgroundColor=10b981',
    established: 'Since 2012',
    stores: 180,
    products: 3400,
    status: 'Active',
  },
  {
    id: '7',
    category: 'Sports',
    name: 'SportMax - Australia',
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=SportMax&backgroundColor=f59e0b',
    established: 'Since 2018',
    stores: 95,
    products: 1800,
    status: 'Pending',
  },
  {
    id: '8',
    category: 'Beauty',
    name: 'GlowBeauty - France',
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=GlowBeauty&backgroundColor=ec4899',
    established: 'Since 2016',
    stores: 250,
    products: 4200,
    status: 'Active',
  },
  {
    id: '9',
    category: 'Food & Beverage',
    name: 'TasteBites - Spain',
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=TasteBites&backgroundColor=ef4444',
    established: 'Since 2008',
    stores: 320,
    products: 2900,
    status: 'Active',
  },
  {
    id: '10',
    category: 'Books',
    name: 'ReadWorld - Japan',
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=ReadWorld&backgroundColor=6366f1',
    established: 'Since 2003',
    stores: 75,
    products: 15000,
    status: 'Inactive',
  },
  {
    id: '11',
    category: 'Toys',
    name: 'PlayZone - Brazil',
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=PlayZone&backgroundColor=14b8a6',
    established: 'Since 2019',
    stores: 110,
    products: 2100,
    status: 'Active',
  },
  {
    id: '12',
    category: 'Jewelry',
    name: 'LuxGems - Switzerland',
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=LuxGems&backgroundColor=f97316',
    established: 'Since 2000',
    stores: 45,
    products: 890,
    status: 'Active',
  },
  {
    id: '13',
    category: 'Pet Supplies',
    name: 'PetParadise - Netherlands',
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=PetParadise&backgroundColor=84cc16',
    established: 'Since 2017',
    stores: 140,
    products: 3100,
    status: 'Pending',
  },
  {
    id: '14',
    category: 'Gaming',
    name: 'GamersHub - South Korea',
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=GamersHub&backgroundColor=a855f7',
    established: 'Since 2021',
    stores: 280,
    products: 5600,
    status: 'Active',
  },
  {
    id: '15',
    category: 'Health',
    name: 'WellnessPlus - Sweden',
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=WellnessPlus&backgroundColor=06b6d4',
    established: 'Since 2014',
    stores: 160,
    products: 2700,
    status: 'Active',
  },
];

export const brandsStats = {
  activeBrands: 69,
  totalBrands: 102,
};
