import type { TotalCardData } from '@/models/dashboard/total-card.model';
import type { Outsource } from '@/models/outsource.model';
import icKOLLayer from '@/assets/icons/dashboard/ic-earning-layer.svg';
import icKOL from '@/assets/icons/dashboard/ic-earning.svg';
import icLeadsLayer from '@/assets/icons/dashboard/ic-number-of-visit-layer.svg';
import icLeads from '@/assets/icons/dashboard/ic-number-of-visit.svg';
import icRevenueLayer from '@/assets/icons/dashboard/ic-total-order-layer.svg';
import icRevenue from '@/assets/icons/dashboard/ic-total-order.svg';
import icCommissionLayer from '@/assets/icons/dashboard/ic-total-return-layer.svg';
import icCommission from '@/assets/icons/dashboard/ic-total-return.svg';

export const outsourceMockup: Outsource[] = [
  {
    id: '1',
    name: 'Casino King Alex',
    type: 'KOL',
    avatar:
      'https://ui-avatars.com/api/?name=Alex+King&background=D32F2F&color=fff',
    specialization: 'Casino',
    platform: 'YouTube + Twitch',
    followers: 850000,
    engagement: 12.5,
    conversionRate: 4.2,
    totalLeads: 8500,
    qualifiedLeads: 6800,
    revenue: 425000,
    commission: 85000,
    commissionRate: 20,
    geo: 'United Kingdom',
    language: 'English',
    status: 'Active',
    tier: 'Diamond',
    contractStart: '2023-01-15',
    contractEnd: '2026-01-15',
    paymentStatus: 'Paid',
    paymentMethod: 'Wire Transfer',
    contactEmail: 'alex@casinoking.com',
    contactPhone: '+44-7700-900123',
    notes: 'Top performer, casino live streams',
  },
  {
    id: '2',
    name: 'Bet Master Network',
    type: 'Agency',
    avatar:
      'https://ui-avatars.com/api/?name=Bet+Master&background=1976D2&color=fff',
    specialization: 'Sports',
    platform: 'Multi-channel',
    followers: 2500000,
    engagement: 8.3,
    conversionRate: 3.5,
    totalLeads: 15000,
    qualifiedLeads: 11250,
    revenue: 680000,
    commission: 136000,
    commissionRate: 20,
    geo: 'Brazil',
    language: 'Portuguese',
    status: 'Active',
    tier: 'Diamond',
    contractStart: '2022-06-01',
    contractEnd: '2025-06-01',
    paymentStatus: 'Paid',
    paymentMethod: 'Bank Transfer',
    contactEmail: 'contact@betmaster.br',
    contactPhone: '+55-11-98765-4321',
    notes: 'Large network, football focus',
  },
  {
    id: '3',
    name: 'Lucky Sarah Gaming',
    type: 'Influencer',
    avatar:
      'https://ui-avatars.com/api/?name=Sarah+Lucky&background=E91E63&color=fff',
    specialization: 'Casino',
    platform: 'Instagram + TikTok',
    followers: 1200000,
    engagement: 15.8,
    conversionRate: 5.1,
    totalLeads: 12000,
    qualifiedLeads: 9600,
    revenue: 520000,
    commission: 104000,
    commissionRate: 20,
    geo: 'Philippines',
    language: 'English',
    status: 'Active',
    tier: 'Platinum',
    contractStart: '2023-08-10',
    contractEnd: '2025-08-10',
    paymentStatus: 'Paid',
    paymentMethod: 'Crypto',
    contactEmail: 'sarah@luckygaming.io',
    contactPhone: '+63-917-123-4567',
    notes: 'Female audience, slots content',
  },
  {
    id: '4',
    name: 'Esports Bet Hub',
    type: 'Affiliate',
    avatar:
      'https://ui-avatars.com/api/?name=Esports+Hub&background=7B1FA2&color=fff',
    specialization: 'Esports',
    platform: 'Discord + Twitter',
    followers: 680000,
    engagement: 18.5,
    conversionRate: 6.2,
    totalLeads: 9500,
    qualifiedLeads: 8075,
    revenue: 485000,
    commission: 97000,
    commissionRate: 20,
    geo: 'South Korea',
    language: 'Korean',
    status: 'Active',
    tier: 'Platinum',
    contractStart: '2024-01-20',
    contractEnd: '2026-01-20',
    paymentStatus: 'Paid',
    paymentMethod: 'Crypto',
    contactEmail: 'contact@esportsbethub.kr',
    contactPhone: '+82-10-1234-5678',
    notes: 'Esports community, high engagement',
  },
  {
    id: '5',
    name: 'Poker Pro Mike',
    type: 'KOL',
    avatar:
      'https://ui-avatars.com/api/?name=Mike+Poker&background=388E3C&color=fff',
    specialization: 'Poker',
    platform: 'YouTube + Facebook',
    followers: 450000,
    engagement: 10.2,
    conversionRate: 3.8,
    totalLeads: 5200,
    qualifiedLeads: 4160,
    revenue: 285000,
    commission: 57000,
    commissionRate: 20,
    geo: 'United States',
    language: 'English',
    status: 'Active',
    tier: 'Gold',
    contractStart: '2023-03-15',
    contractEnd: '2025-03-15',
    paymentStatus: 'Paid',
    paymentMethod: 'Wire Transfer',
    contactEmail: 'mike@pokerpro.us',
    contactPhone: '+1-702-555-9876',
    notes: 'Poker tournaments, strategy content',
  },
  {
    id: '6',
    name: 'Global Bet Partners',
    type: 'Agency',
    avatar:
      'https://ui-avatars.com/api/?name=Global+Partners&background=F57C00&color=fff',
    specialization: 'Multi-vertical',
    platform: 'Multi-channel',
    followers: 3200000,
    engagement: 6.5,
    conversionRate: 2.8,
    totalLeads: 18000,
    qualifiedLeads: 12600,
    revenue: 825000,
    commission: 165000,
    commissionRate: 20,
    geo: 'Malta',
    language: 'Multi-language',
    status: 'Active',
    tier: 'Diamond',
    contractStart: '2021-09-01',
    contractEnd: '2025-09-01',
    paymentStatus: 'Paid',
    paymentMethod: 'Bank Transfer',
    contactEmail: 'info@globalbetpartners.com',
    contactPhone: '+356-2123-4567',
    notes: 'Largest partner, multi-vertical',
  },
  {
    id: '7',
    name: 'Football Betting Expert',
    type: 'Influencer',
    avatar:
      'https://ui-avatars.com/api/?name=Football+Expert&background=00695C&color=fff',
    specialization: 'Sports',
    platform: 'Telegram + Twitter',
    followers: 320000,
    engagement: 22.5,
    conversionRate: 7.8,
    totalLeads: 6800,
    qualifiedLeads: 5780,
    revenue: 395000,
    commission: 79000,
    commissionRate: 20,
    geo: 'Spain',
    language: 'Spanish',
    status: 'Active',
    tier: 'Platinum',
    contractStart: '2023-11-05',
    contractEnd: '2025-11-05',
    paymentStatus: 'Paid',
    paymentMethod: 'Bank Transfer',
    contactEmail: 'expert@footballbet.es',
    contactPhone: '+34-600-123-456',
    notes: 'Football predictions, VIP tips',
  },
  {
    id: '8',
    name: 'Asia Casino Network',
    type: 'Partner',
    avatar:
      'https://ui-avatars.com/api/?name=Asia+Casino&background=C62828&color=fff',
    specialization: 'Casino',
    platform: 'WeChat + Website',
    followers: 1850000,
    engagement: 9.5,
    conversionRate: 4.5,
    totalLeads: 14500,
    qualifiedLeads: 11600,
    revenue: 685000,
    commission: 137000,
    commissionRate: 20,
    geo: 'China',
    language: 'Chinese',
    status: 'Active',
    tier: 'Platinum',
    contractStart: '2022-12-10',
    contractEnd: '2025-12-10',
    paymentStatus: 'Paid',
    paymentMethod: 'Crypto',
    contactEmail: 'contact@asiacasino.cn',
    contactPhone: '+86-138-0000-1234',
    notes: 'Asian market leader, live casino',
  },
  {
    id: '9',
    name: 'Crypto Bet Influencer',
    type: 'KOL',
    avatar:
      'https://ui-avatars.com/api/?name=Crypto+Bet&background=4A148C&color=fff',
    specialization: 'Casino',
    platform: 'Twitter + Medium',
    followers: 580000,
    engagement: 14.2,
    conversionRate: 5.5,
    totalLeads: 7200,
    qualifiedLeads: 5760,
    revenue: 425000,
    commission: 85000,
    commissionRate: 20,
    geo: 'Global',
    language: 'English',
    status: 'Active',
    tier: 'Gold',
    contractStart: '2024-02-01',
    contractEnd: '2026-02-01',
    paymentStatus: 'Paid',
    paymentMethod: 'Crypto',
    contactEmail: 'crypto@betinfluencer.io',
    contactPhone: '+1-415-555-7890',
    notes: 'Crypto-focused, blockchain casinos',
  },
  {
    id: '10',
    name: 'Slots Queen Emma',
    type: 'Influencer',
    avatar:
      'https://ui-avatars.com/api/?name=Emma+Queen&background=F57F17&color=fff',
    specialization: 'Casino',
    platform: 'YouTube + Instagram',
    followers: 720000,
    engagement: 16.8,
    conversionRate: 6.1,
    totalLeads: 8900,
    qualifiedLeads: 7120,
    revenue: 485000,
    commission: 97000,
    commissionRate: 20,
    geo: 'Germany',
    language: 'German',
    status: 'Active',
    tier: 'Platinum',
    contractStart: '2023-05-20',
    contractEnd: '2025-05-20',
    paymentStatus: 'Paid',
    paymentMethod: 'Bank Transfer',
    contactEmail: 'emma@slotsqueen.de',
    contactPhone: '+49-176-1234-5678',
    notes: 'Slot machine specialist, big wins content',
  },
  {
    id: '11',
    name: 'Betting Tips Network',
    type: 'Affiliate',
    avatar:
      'https://ui-avatars.com/api/?name=Tips+Network&background=0277BD&color=fff',
    specialization: 'Sports',
    platform: 'Website + Email',
    followers: 425000,
    engagement: 8.5,
    conversionRate: 3.2,
    totalLeads: 4850,
    qualifiedLeads: 3880,
    revenue: 265000,
    commission: 53000,
    commissionRate: 20,
    geo: 'Australia',
    language: 'English',
    status: 'Active',
    tier: 'Gold',
    contractStart: '2023-07-01',
    contractEnd: '2025-07-01',
    paymentStatus: 'Paid',
    paymentMethod: 'PayPal',
    contactEmail: 'info@bettingtips.au',
    contactPhone: '+61-400-123-456',
    notes: 'Daily tips, newsletter subscribers',
  },
  {
    id: '12',
    name: 'VIP Casino Blogger',
    type: 'KOL',
    avatar:
      'https://ui-avatars.com/api/?name=VIP+Blogger&background=5D4037&color=fff',
    specialization: 'Casino',
    platform: 'Blog + YouTube',
    followers: 280000,
    engagement: 11.5,
    conversionRate: 4.8,
    totalLeads: 3800,
    qualifiedLeads: 3040,
    revenue: 195000,
    commission: 39000,
    commissionRate: 20,
    geo: 'Canada',
    language: 'English',
    status: 'Pending',
    tier: 'Silver',
    contractStart: '2025-09-15',
    contractEnd: '2026-09-15',
    paymentStatus: 'Pending',
    paymentMethod: 'Bank Transfer',
    contactEmail: 'blogger@vipcasino.ca',
    contactPhone: '+1-416-555-3456',
    notes: 'New partner, performance monitoring',
  },
];

export const outsourceStats = {
  totalPartners: outsourceMockup.length,
  activePartners: outsourceMockup.filter((o) => o.status === 'Active').length,
  totalLeads: outsourceMockup.reduce((sum, o) => sum + o.totalLeads, 0),
  qualifiedLeads: outsourceMockup.reduce((sum, o) => sum + o.qualifiedLeads, 0),
  totalRevenue: outsourceMockup.reduce((sum, o) => sum + o.revenue, 0),
  totalCommission: outsourceMockup.reduce((sum, o) => sum + o.commission, 0),
  averageConversionRate:
    outsourceMockup.reduce((sum, o) => sum + o.conversionRate, 0) /
    outsourceMockup.length,
  diamondTier: outsourceMockup.filter((o) => o.tier === 'Diamond').length,
};

// Total cards for outsource page
export const totalCardsOutsourceMockup: TotalCardData[] = [
  {
    id: '1',
    title: 'Active Partners',
    value: '125',
    icon: icKOL,
    percentageChange: 15.2,
    changeLabel: 'Since last month',
    layer: icKOLLayer,
  },
  {
    id: '2',
    title: 'Total Leads',
    value: '114.3K',
    icon: icLeads,
    percentageChange: 28.5,
    changeLabel: 'Since last month',
    layer: icLeadsLayer,
  },
  {
    id: '3',
    title: 'Total Revenue',
    value: '$5.67M',
    icon: icRevenue,
    percentageChange: 35.8,
    changeLabel: 'Since last month',
    layer: icRevenueLayer,
  },
  {
    id: '4',
    title: 'Total Commission',
    value: '$1.13M',
    icon: icCommission,
    percentageChange: 35.8,
    changeLabel: 'Since last month',
    layer: icCommissionLayer,
  },
];
