import type { TFunction } from 'i18next';
import type { TotalCardData } from '@/models/dashboard/total-card.model';
import type { Publisher } from '@/models/employees.model';
import icPublisherLayer from '@/assets/icons/dashboard/ic-earning-layer.svg';
// Import icons (you'll need to create or use existing icons)
import icPublisher from '@/assets/icons/dashboard/ic-earning.svg';
import icActiveLayer from '@/assets/icons/dashboard/ic-number-of-visit-layer.svg';
import icActive from '@/assets/icons/dashboard/ic-number-of-visit.svg';
import icRevenueLayer from '@/assets/icons/dashboard/ic-total-order-layer.svg';
import icRevenue from '@/assets/icons/dashboard/ic-total-order.svg';
import icFillRateLayer from '@/assets/icons/dashboard/ic-total-return-layer.svg';
import icFillRate from '@/assets/icons/dashboard/ic-total-return.svg';

export const publishersMockup: Publisher[] = [
  {
    id: '1',
    websiteName: 'BetMaster Pro',
    domain: 'betmasterpro.com',
    logo: 'https://ui-avatars.com/api/?name=BetMaster+Pro&background=D32F2F&color=fff',
    category: 'Sports Betting',
    status: 'Active',
    monthlyVisitors: 4200000,
    pageViews: 15800000,
    revenue: 125000,
    adSlots: 18,
    fillRate: 96.5,
    cpm: 12.5,
    rpm: 12.06,
    contactEmail: 'contact@betmasterpro.com',
    contactPerson: 'David Chen',
    phone: '+44-20-7946-1234',
    country: 'United Kingdom',
    language: 'English',
    dateAdded: '2022-01-15',
    lastUpdated: '2025-10-14',
    paymentStatus: 'Paid',
    paymentMethod: 'Wire Transfer',
    notes: 'Premium sports betting platform, high conversion',
  },
  {
    id: '2',
    websiteName: 'Casino Elite 777',
    domain: 'casinoelite777.net',
    logo: 'https://ui-avatars.com/api/?name=Casino+Elite&background=C62828&color=fff',
    category: 'Casino & Slots',
    status: 'Active',
    monthlyVisitors: 3800000,
    pageViews: 14200000,
    revenue: 158000,
    adSlots: 20,
    fillRate: 98.2,
    cpm: 15.8,
    rpm: 15.52,
    contactEmail: 'info@casinoelite777.net',
    contactPerson: 'Marcus Williams',
    phone: '+356-2133-4567',
    country: 'Malta',
    language: 'English',
    dateAdded: '2022-03-22',
    lastUpdated: '2025-10-13',
    paymentStatus: 'Paid',
    paymentMethod: 'Bank Transfer',
    notes: 'Top-tier casino, VIP players',
  },
  {
    id: '3',
    websiteName: 'Live Casino Asia',
    domain: 'livecasinoasia.io',
    logo: 'https://ui-avatars.com/api/?name=Live+Casino&background=E65100&color=fff',
    category: 'Live Casino',
    status: 'Active',
    monthlyVisitors: 5200000,
    pageViews: 20800000,
    revenue: 185000,
    adSlots: 22,
    fillRate: 97.8,
    cpm: 18.2,
    rpm: 17.8,
    contactEmail: 'admin@livecasinoasia.io',
    contactPerson: 'Li Wei',
    phone: '+63-2-8888-9999',
    country: 'Philippines',
    language: 'Multi-language',
    dateAdded: '2021-11-08',
    lastUpdated: '2025-10-14',
    paymentStatus: 'Paid',
    paymentMethod: 'Crypto',
    notes: 'Asian market leader, live dealers',
  },
  {
    id: '4',
    websiteName: 'Poker Champions Club',
    domain: 'pokerchampions.club',
    logo: 'https://ui-avatars.com/api/?name=Poker+Club&background=1976D2&color=fff',
    category: 'Poker & Card Games',
    status: 'Active',
    monthlyVisitors: 2100000,
    pageViews: 8900000,
    revenue: 78000,
    adSlots: 14,
    fillRate: 94.3,
    cpm: 11.5,
    rpm: 10.84,
    contactEmail: 'support@pokerchampions.club',
    contactPerson: 'James Rodriguez',
    phone: '+1-702-555-0101',
    country: 'United States',
    language: 'English',
    dateAdded: '2023-09-15',
    lastUpdated: '2025-10-12',
    paymentStatus: 'Paid',
    paymentMethod: 'Wire Transfer',
    notes: 'Poker tournaments, pro players',
  },
  {
    id: '5',
    websiteName: 'Esports Betting Hub',
    domain: 'esportsbettinghub.gg',
    logo: 'https://ui-avatars.com/api/?name=Esports+Hub&background=7B1FA2&color=fff',
    category: 'Esports Betting',
    status: 'Active',
    monthlyVisitors: 3600000,
    pageViews: 16200000,
    revenue: 142000,
    adSlots: 19,
    fillRate: 96.1,
    cpm: 13.8,
    rpm: 13.26,
    contactEmail: 'hello@esportsbettinghub.gg',
    contactPerson: 'Sarah Kim',
    phone: '+82-2-1234-5678',
    country: 'South Korea',
    language: 'English',
    dateAdded: '2023-05-10',
    lastUpdated: '2025-10-14',
    paymentStatus: 'Paid',
    paymentMethod: 'PayPal',
    notes: 'Young demographic, high engagement',
  },
  {
    id: '6',
    websiteName: 'Slots Paradise VIP',
    domain: 'slotsparadisevip.com',
    logo: 'https://ui-avatars.com/api/?name=Slots+VIP&background=F57C00&color=fff',
    category: 'Slot Games',
    status: 'Active',
    monthlyVisitors: 2900000,
    pageViews: 12500000,
    revenue: 96000,
    adSlots: 16,
    fillRate: 95.7,
    cpm: 14.2,
    rpm: 13.59,
    contactEmail: 'contact@slotsparadisevip.com',
    contactPerson: 'Anna Petrova',
    phone: '+7-495-123-4567',
    country: 'Russia',
    language: 'Russian',
    dateAdded: '2023-07-18',
    lastUpdated: '2025-10-13',
    paymentStatus: 'Paid',
    paymentMethod: 'Bank Transfer',
    notes: 'Progressive jackpots, high retention',
  },
  {
    id: '7',
    websiteName: 'Football Bet World',
    domain: 'footballbetworld.bet',
    logo: 'https://ui-avatars.com/api/?name=Football+Bet&background=388E3C&color=fff',
    category: 'Sports Betting',
    status: 'Active',
    monthlyVisitors: 4800000,
    pageViews: 19200000,
    revenue: 168000,
    adSlots: 21,
    fillRate: 97.2,
    cpm: 16.5,
    rpm: 16.04,
    contactEmail: 'info@footballbetworld.bet',
    contactPerson: 'Ricardo Silva',
    phone: '+55-11-3456-7890',
    country: 'Brazil',
    language: 'Portuguese',
    dateAdded: '2022-09-25',
    lastUpdated: '2025-10-14',
    paymentStatus: 'Paid',
    paymentMethod: 'Wire Transfer',
    notes: 'Football focus, Latin America',
  },
  {
    id: '8',
    websiteName: 'Lucky Spin Casino',
    domain: 'luckyspincasino.org',
    logo: 'https://ui-avatars.com/api/?name=Lucky+Spin&background=D32F2F&color=fff',
    category: 'Casino & Slots',
    status: 'Pending',
    monthlyVisitors: 1800000,
    pageViews: 7200000,
    revenue: 65000,
    adSlots: 12,
    fillRate: 89.5,
    cpm: 10.8,
    rpm: 9.67,
    contactEmail: 'admin@luckyspincasino.org',
    contactPerson: 'Mohammed Al-Rashid',
    phone: '+971-4-123-4567',
    country: 'UAE',
    language: 'Arabic',
    dateAdded: '2025-09-14',
    lastUpdated: '2025-10-08',
    paymentStatus: 'Pending',
    paymentMethod: 'Bank Transfer',
    notes: 'New market entry, compliance check',
  },
  {
    id: '9',
    websiteName: 'Racing Odds Expert',
    domain: 'racingoddexpert.com',
    logo: 'https://ui-avatars.com/api/?name=Racing+Odds&background=5D4037&color=fff',
    category: 'Horse Racing',
    status: 'Active',
    monthlyVisitors: 1500000,
    pageViews: 6000000,
    revenue: 58000,
    adSlots: 11,
    fillRate: 91.8,
    cpm: 11.2,
    rpm: 10.28,
    contactEmail: 'support@racingoddexpert.com',
    contactPerson: "Patrick O'Brien",
    phone: '+353-1-234-5678',
    country: 'Ireland',
    language: 'English',
    dateAdded: '2023-04-05',
    lastUpdated: '2025-10-11',
    paymentStatus: 'Paid',
    paymentMethod: 'Bank Transfer',
    notes: 'Horse racing niche, loyal users',
  },
  {
    id: '10',
    websiteName: 'Baccarat Royal',
    domain: 'baccaratroyal.vip',
    logo: 'https://ui-avatars.com/api/?name=Baccarat+Royal&background=4A148C&color=fff',
    category: 'Live Casino',
    status: 'Active',
    monthlyVisitors: 3200000,
    pageViews: 14400000,
    revenue: 135000,
    adSlots: 17,
    fillRate: 96.9,
    cpm: 17.5,
    rpm: 16.96,
    contactEmail: 'contact@baccaratroyal.vip',
    contactPerson: 'Zhang Ming',
    phone: '+86-21-6789-0123',
    country: 'China',
    language: 'Chinese',
    dateAdded: '2022-12-20',
    lastUpdated: '2025-10-14',
    paymentStatus: 'Paid',
    paymentMethod: 'Crypto',
    notes: 'VIP baccarat, high rollers',
  },
  {
    id: '11',
    websiteName: 'Bet365 Affiliate Network',
    domain: 'bet365partners.net',
    logo: 'https://ui-avatars.com/api/?name=Bet365+Network&background=00695C&color=fff',
    category: 'Sports Betting',
    status: 'Active',
    monthlyVisitors: 6500000,
    pageViews: 26000000,
    revenue: 215000,
    adSlots: 25,
    fillRate: 98.5,
    cpm: 19.8,
    rpm: 19.5,
    contactEmail: 'info@bet365partners.net',
    contactPerson: 'Elizabeth Turner',
    phone: '+44-161-123-4567',
    country: 'United Kingdom',
    language: 'English',
    dateAdded: '2021-06-12',
    lastUpdated: '2025-10-14',
    paymentStatus: 'Paid',
    paymentMethod: 'Wire Transfer',
    notes: 'Industry leader, global reach',
  },
  {
    id: '12',
    websiteName: 'Lottery & Betting Hub',
    domain: 'lotterybettinghub.com',
    logo: 'https://ui-avatars.com/api/?name=Lottery+Hub&background=F57F17&color=fff',
    category: 'Lottery & Numbers',
    status: 'Suspended',
    monthlyVisitors: 980000,
    pageViews: 3920000,
    revenue: 32000,
    adSlots: 9,
    fillRate: 82.3,
    cpm: 8.5,
    rpm: 6.99,
    contactEmail: 'hello@lotterybettinghub.com',
    contactPerson: 'Maria Santos',
    phone: '+34-91-765-4321',
    country: 'Spain',
    language: 'Spanish',
    dateAdded: '2023-08-30',
    lastUpdated: '2025-09-20',
    paymentStatus: 'Overdue',
    paymentMethod: 'PayPal',
    notes: 'Suspended - license verification needed',
  },
];

export const publisherStats = {
  totalPublishers: publishersMockup.length,
  activePublishers: publishersMockup.filter((p) => p.status === 'Active')
    .length,
  pendingPublishers: publishersMockup.filter((p) => p.status === 'Pending')
    .length,
  suspendedPublishers: publishersMockup.filter((p) => p.status === 'Suspended')
    .length,
  totalRevenue: publishersMockup.reduce((sum, p) => sum + p.revenue, 0),
  averageCPM:
    publishersMockup.reduce((sum, p) => sum + p.cpm, 0) /
    publishersMockup.length,
  averageFillRate:
    publishersMockup.reduce((sum, p) => sum + p.fillRate, 0) /
    publishersMockup.length,
};

// Total cards for publisher page - Now with i18n support
export const getTotalCardsPublisherMockup = (t: TFunction): TotalCardData[] => [
  {
    id: '1',
    title: t('total_publishers'),
    value: '156',
    icon: icPublisher,
    percentageChange: 12.5,
    changeLabel: t('since_last_month'),
    layer: icPublisherLayer,
  },
  {
    id: '2',
    title: t('active_publishers'),
    value: '128',
    icon: icActive,
    percentageChange: 8.3,
    changeLabel: t('since_last_month'),
    layer: icActiveLayer,
  },
  {
    id: '3',
    title: t('total_revenue'),
    value: '$842,350',
    icon: icRevenue,
    percentageChange: 22.8,
    changeLabel: t('since_last_month'),
    layer: icRevenueLayer,
  },
  {
    id: '4',
    title: t('average_fill_rate'),
    value: '87.6%',
    icon: icFillRate,
    percentageChange: 5.4,
    changeLabel: t('since_last_month'),
    layer: icFillRateLayer,
  },
];

// Keep the old export for backwards compatibility
export const totalCardsPublisherMockup: TotalCardData[] = [
  {
    id: '1',
    title: 'Total Publishers',
    value: '156',
    icon: icPublisher,
    percentageChange: 12.5,
    changeLabel: 'Since last month',
    layer: icPublisherLayer,
  },
  {
    id: '2',
    title: 'Active Publishers',
    value: '128',
    icon: icActive,
    percentageChange: 8.3,
    changeLabel: 'Since last month',
    layer: icActiveLayer,
  },
  {
    id: '3',
    title: 'Total Revenue',
    value: '$842,350',
    icon: icRevenue,
    percentageChange: 22.8,
    changeLabel: 'Since last month',
    layer: icRevenueLayer,
  },
  {
    id: '4',
    title: 'Avg Fill Rate',
    value: '87.6%',
    icon: icFillRate,
    percentageChange: 5.4,
    changeLabel: 'Since last month',
    layer: icFillRateLayer,
  },
];
