import type { TFunction } from 'i18next';
import type { TotalCardData } from '@/models/dashboard/total-card.model';
import type { Traffic } from '@/models/traffic.model';
import icClicksLayer from '@/assets/icons/dashboard/ic-earning-layer.svg';
import icClicks from '@/assets/icons/dashboard/ic-earning.svg';
import icConversionsLayer from '@/assets/icons/dashboard/ic-number-of-visit-layer.svg';
import icConversions from '@/assets/icons/dashboard/ic-number-of-visit.svg';
import icRevenueLayer from '@/assets/icons/dashboard/ic-total-order-layer.svg';
import icRevenue from '@/assets/icons/dashboard/ic-total-order.svg';
import icROILayer from '@/assets/icons/dashboard/ic-total-return-layer.svg';
import icROI from '@/assets/icons/dashboard/ic-total-return.svg';

export const trafficMockup: Traffic[] = [
  {
    id: '1',
    source: 'Google Ads - Casino Keywords',
    platform: 'Google Ads',
    category: 'Casino',
    geoLocation: 'United Kingdom',
    clicks: 125000,
    conversions: 3250,
    conversionRate: 2.6,
    cpc: 3.5,
    cpa: 135.0,
    revenue: 485000,
    profit: 46250,
    roi: 10.5,
    quality: 'Premium',
    deviceType: 'Mixed',
    targetAudience: '25-45, Male, High Income',
    status: 'Active',
    startDate: '2024-01-15',
    lastActivity: '2025-10-14',
    notes: 'High-quality casino traffic, strong ROI',
  },
  {
    id: '2',
    source: 'Facebook Ads - Sports Betting',
    platform: 'Facebook',
    category: 'Sports Betting',
    geoLocation: 'Brazil',
    clicks: 280000,
    conversions: 8400,
    conversionRate: 3.0,
    cpc: 1.2,
    cpa: 40.0,
    revenue: 520000,
    profit: 184000,
    roi: 54.8,
    quality: 'Premium',
    deviceType: 'Mobile',
    targetAudience: '18-35, Male, Sports Fans',
    status: 'Active',
    startDate: '2024-03-10',
    lastActivity: '2025-10-14',
    notes: 'Football season driving high conversions',
  },
  {
    id: '3',
    source: 'Native Ads - Slot Games',
    platform: 'Taboola',
    category: 'Slot Games',
    geoLocation: 'Germany',
    clicks: 95000,
    conversions: 1900,
    conversionRate: 2.0,
    cpc: 2.8,
    cpa: 140.0,
    revenue: 315000,
    profit: 49000,
    roi: 18.4,
    quality: 'Standard',
    deviceType: 'Desktop',
    targetAudience: '35-55, Mixed Gender',
    status: 'Active',
    startDate: '2024-05-20',
    lastActivity: '2025-10-13',
    notes: 'Steady performance, older demographic',
  },
  {
    id: '4',
    source: 'TikTok Ads - Esports',
    platform: 'TikTok',
    category: 'Sports Betting',
    geoLocation: 'South Korea',
    clicks: 185000,
    conversions: 5550,
    conversionRate: 3.0,
    cpc: 0.8,
    cpa: 26.7,
    revenue: 425000,
    profit: 277000,
    roi: 187.1,
    quality: 'Premium',
    deviceType: 'Mobile',
    targetAudience: '18-25, Male, Gamers',
    status: 'Active',
    startDate: '2024-07-01',
    lastActivity: '2025-10-14',
    notes: 'Excellent ROI, young esports audience',
  },
  {
    id: '5',
    source: 'Instagram Stories - Live Casino',
    platform: 'Instagram',
    category: 'Live Casino',
    geoLocation: 'Philippines',
    clicks: 220000,
    conversions: 6600,
    conversionRate: 3.0,
    cpc: 1.5,
    cpa: 50.0,
    revenue: 680000,
    profit: 350000,
    roi: 106.1,
    quality: 'Premium',
    deviceType: 'Mobile',
    targetAudience: '25-40, Mixed Gender',
    status: 'Active',
    startDate: '2024-02-14',
    lastActivity: '2025-10-14',
    notes: 'Live dealer content performs well',
  },
  {
    id: '6',
    source: 'YouTube Pre-roll - Poker',
    platform: 'YouTube',
    category: 'Poker',
    geoLocation: 'United States',
    clicks: 75000,
    conversions: 1125,
    conversionRate: 1.5,
    cpc: 4.2,
    cpa: 280.0,
    revenue: 395000,
    profit: 80000,
    roi: 25.4,
    quality: 'Standard',
    deviceType: 'Desktop',
    targetAudience: '30-50, Male, Poker Players',
    status: 'Active',
    startDate: '2024-06-08',
    lastActivity: '2025-10-12',
    notes: 'High CPA but quality leads',
  },
  {
    id: '7',
    source: 'Push Notifications - Casino',
    platform: 'PropellerAds',
    category: 'Casino',
    geoLocation: 'Russia',
    clicks: 320000,
    conversions: 6400,
    conversionRate: 2.0,
    cpc: 0.5,
    cpa: 25.0,
    revenue: 285000,
    profit: 125000,
    roi: 78.1,
    quality: 'Standard',
    deviceType: 'Mobile',
    targetAudience: '25-45, Male',
    status: 'Active',
    startDate: '2024-04-12',
    lastActivity: '2025-10-14',
    notes: 'Low CPC, good volume',
  },
  {
    id: '8',
    source: 'Email Marketing - VIP Casino',
    platform: 'Internal Database',
    category: 'Casino',
    geoLocation: 'Malta',
    clicks: 45000,
    conversions: 1350,
    conversionRate: 3.0,
    cpc: 0.2,
    cpa: 6.7,
    revenue: 425000,
    profit: 416000,
    roi: 4622.2,
    quality: 'Premium',
    deviceType: 'Mixed',
    targetAudience: 'VIP Players, High Rollers',
    status: 'Active',
    startDate: '2023-01-01',
    lastActivity: '2025-10-13',
    notes: 'Highest ROI, existing customer base',
  },
  {
    id: '9',
    source: 'Twitter Ads - Sports Events',
    platform: 'Twitter/X',
    category: 'Sports Betting',
    geoLocation: 'United Kingdom',
    clicks: 165000,
    conversions: 3300,
    conversionRate: 2.0,
    cpc: 2.1,
    cpa: 105.0,
    revenue: 385000,
    profit: 38500,
    roi: 11.1,
    quality: 'Standard',
    deviceType: 'Mobile',
    targetAudience: '20-40, Male, Sports Fans',
    status: 'Active',
    startDate: '2024-08-15',
    lastActivity: '2025-10-14',
    notes: 'Event-based campaigns perform best',
  },
  {
    id: '10',
    source: 'SEO Organic - Betting Reviews',
    platform: 'Organic Search',
    category: 'Sports Betting',
    geoLocation: 'Australia',
    clicks: 95000,
    conversions: 2850,
    conversionRate: 3.0,
    cpc: 0.0,
    cpa: 0.0,
    revenue: 320000,
    profit: 320000,
    roi: 999.9,
    quality: 'Premium',
    deviceType: 'Desktop',
    targetAudience: '25-50, Mixed Gender',
    status: 'Active',
    startDate: '2023-06-01',
    lastActivity: '2025-10-14',
    notes: 'Organic traffic, no ad spend',
  },
  {
    id: '11',
    source: 'Telegram Ads - Crypto Casino',
    platform: 'Telegram',
    category: 'Casino',
    geoLocation: 'Global',
    clicks: 280000,
    conversions: 5600,
    conversionRate: 2.0,
    cpc: 0.6,
    cpa: 30.0,
    revenue: 445000,
    profit: 277000,
    roi: 164.9,
    quality: 'Premium',
    deviceType: 'Mobile',
    targetAudience: 'Crypto Users, 20-40',
    status: 'Active',
    startDate: '2024-09-01',
    lastActivity: '2025-10-14',
    notes: 'Crypto payment users, high engagement',
  },
  {
    id: '12',
    source: 'Affiliate Network - Multi-vertical',
    platform: 'CJ Affiliate',
    category: 'Sports Betting',
    geoLocation: 'Canada',
    clicks: 125000,
    conversions: 2500,
    conversionRate: 2.0,
    cpc: 1.8,
    cpa: 90.0,
    revenue: 295000,
    profit: 70000,
    roi: 31.1,
    quality: 'Standard',
    deviceType: 'Mixed',
    targetAudience: '25-45, Male',
    status: 'Testing',
    startDate: '2025-09-15',
    lastActivity: '2025-10-10',
    notes: 'Testing phase, monitoring performance',
  },
];

export const trafficStats = {
  totalClicks: trafficMockup.reduce((sum, t) => sum + t.clicks, 0),
  totalConversions: trafficMockup.reduce((sum, t) => sum + t.conversions, 0),
  totalRevenue: trafficMockup.reduce((sum, t) => sum + t.revenue, 0),
  totalProfit: trafficMockup.reduce((sum, t) => sum + t.profit, 0),
  averageConversionRate:
    trafficMockup.reduce((sum, t) => sum + t.conversionRate, 0) /
    trafficMockup.length,
  averageROI:
    trafficMockup.reduce((sum, t) => sum + t.roi, 0) / trafficMockup.length,
  activeSources: trafficMockup.filter((t) => t.status === 'Active').length,
};

// Total cards for traffic page - Now with i18n support
export const getTotalCardsTrafficMockup = (t: TFunction): TotalCardData[] => [
  {
    id: '1',
    title: t('total_clicks'),
    value: '2.01M',
    icon: icClicks,
    percentageChange: 18.5,
    changeLabel: t('since_last_month'),
    layer: icClicksLayer,
  },
  {
    id: '2',
    title: t('total_conversions'),
    value: '48.8K',
    icon: icConversions,
    percentageChange: 24.2,
    changeLabel: t('since_last_month'),
    layer: icConversionsLayer,
  },
  {
    id: '3',
    title: t('total_revenue'),
    value: '$4.97M',
    icon: icRevenue,
    percentageChange: 32.6,
    changeLabel: t('since_last_month'),
    layer: icRevenueLayer,
  },
  {
    id: '4',
    title: t('average_roi'),
    value: '291.6%',
    icon: icROI,
    percentageChange: 15.8,
    changeLabel: t('since_last_month'),
    layer: icROILayer,
  },
];

// Keep the old export for backwards compatibility
export const totalCardsTrafficMockup: TotalCardData[] = [
  {
    id: '1',
    title: 'Total Clicks',
    value: '2.01M',
    icon: icClicks,
    percentageChange: 18.5,
    changeLabel: 'Since last month',
    layer: icClicksLayer,
  },
  {
    id: '2',
    title: 'Total Conversions',
    value: '48.8K',
    icon: icConversions,
    percentageChange: 24.2,
    changeLabel: 'Since last month',
    layer: icConversionsLayer,
  },
  {
    id: '3',
    title: 'Total Revenue',
    value: '$4.97M',
    icon: icRevenue,
    percentageChange: 32.6,
    changeLabel: 'Since last month',
    layer: icRevenueLayer,
  },
  {
    id: '4',
    title: 'Average ROI',
    value: '291.6%',
    icon: icROI,
    percentageChange: 15.8,
    changeLabel: 'Since last month',
    layer: icROILayer,
  },
];
